name: Run tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    container:
      image: node:20

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸŒ Setup Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true

      - name: ğŸš€ Start Python HTTP Server
        run: |
          cd src
          nohup python3 -m http.server 8000 > http_server.log 2>&1 &

      - name: â³ Wait for Server to be Ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8000; do
            echo "Waiting for server to start..."
            sleep 1
          done
          echo "Server is up!"

      - name: ğŸ“¦ Install Dependencies
        run: |
          cd tests
          npm install

      - name: ğŸ› ï¸ Fix Permissions for Mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: ğŸ§ª Run Mocha Tests
        run: |
          cd tests
          npm test

      - name: ğŸ“¤ Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
